version: '2'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - zammad
    links:
      - zammad
    ports:
      - "80:80"
    restart: always
    volumes:
      - data-zammad:/home/zammad
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    restart: always
  zammad:
    build:
      context: .
      dockerfile: Dockerfile.zammad
    depends_on:
      - postgresql
      - elasticsearch
    links:
      - postgresql
      - elasticsearch
    restart: always
    volumes:
      - data-zammad:/home/zammad
volumes:
  data-zammad:
    driver: local
